services:

  girder:
    volumes:
      - ./server:/opt/dive/src
      - ./docker/server_setup.py:/server_setup.py
    command: ["--mode", "development"]

  girder_worker_default:
    volumes:
      - ./server:/opt/dive/src
