version: "3.8"
services:
  dive-dsa-slicer:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HF_TOKEN: ${HF_TOKEN:-}
    image: ghcr.io/digitalslidearchive/dive-dsa/dive-dsa-slicer-examples:${TAG:-latest}

