name: NPM Publish DIVE-DSA-Slicer
on:
  workflow_dispatch: 
  release:
    types: [published]

jobs:
 build:
    runs-on: ubuntu-latest
    name: Publish Vue Girder SlicerCLI UI Client Library
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        working-directory: ./dive-dsa-slicer/vue-girder-slicer-ui  
      - run: npm run build
        working-directory: ./dive-dsa-slicer/vue-girder-slicer-ui
      - run: npm publish
        working-directory: ./dive-dsa-slicer/vue-girder-slicer-ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
