name: Build Docker Images
on:
  workflow_dispatch: 
  push:
    branches:
      - main
jobs:
  publish:
    name: Publish Docker Container
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push web
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/girder.Dockerfile
          tags: ghcr.io/digitalslidearchive/dive-dsa/dive-dsa-web:latest
          push: true
      -
        name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/girder_worker.Dockerfile
          tags: ghcr.io/digitalslidearchive/dive-dsa/dive-dsa-worker:latest
          push: true

  docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # "ref" specifies the branch to check out.
        # "github.event.release.target_commitish" is a global variable and specifies the branch the release targeted
        ref: ${{ github.event.release.target_commitish }}

    # Deploy docs
    - name: Deploy docs
      uses: mhausenblas/mkdocs-deploy-gh-pages@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_FILE: mkdocs.yml
        EXTRA_PACKAGES: build-base
